# Generated by Django 3.1.1 on 2020-09-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morweb', '0002_auto_20200906_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mtags',
            field=models.ManyToManyField(related_name='movie_tags', to='morweb.TagClass'),
        ),
    ]
