# Generated by Django 3.1.1 on 2020-09-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morweb', '0003_movie_mtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='morweb.TagClass'),
        ),
    ]
