# Generated by Django 3.1.1 on 2020-09-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morweb', '0004_auto_20200906_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='words',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
